FROM debian

# install during creation of the image
# inline because apt-get won't have access to previous layers after run command
RUN apt-get update && apt-get install -y apache2 && apt-get clean
ENV APACHE_LOCK_DIR "/var/lock"
ENV APACHE_PID_FILE "/var/run/apache2.pid"
ENV APACHE_RUN_USER "www-data"
ENV APACHE_RUN_GROUP "www-data"
ENV APACHE_LOG_DIR "/var/log/apache2"

LABEL description="Webserver"

VOLUME /var/www/html

EXPOSE 80

# instruction is used to set executables that will always run when the container is initiated
ENTRYPOINT [ "/usr/sbin/apachectl" ]

# instruction is used to set default arguments for the ENTRYPOINT instruction
CMD [ "-D", "FOREGROUND" ]
